event:
    resource: "routing/event.yml"
    prefix:   /event

connection:
    resource: "routing/connection.yml"
    prefix: /connect

admin:
    resource: "routing/admin.yml"
    prefix: /admin

association:
    resource: "routing/site.yml"
    prefix: /association
