# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        github_user:
            id: "github_user_repository"
        legacy_user:
            id: "app.user_repository"
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        legacy_secured_area:
            anonymous: ~
            pattern: ^(/admin/|/event/\w+/tickets)
            logout:
                path:   /admin/logout
                target: /
            guard:
                authenticators:
                    - app.legacy_authenticator
                    - app.legacy_hash_authenticator
                entry_point: app.legacy_authenticator

        github_secured_area:
            pattern: ^(/event/.*/(vote|cfp)|/connect/github/check)

            guard:
                authenticators:
                    - my_github_authenticator
                entry_point: my_github_authenticator

        main:
            anonymous: ~

    access_control:
        - { path: ^/event/vote/, roles: ROLE_GITHUB }
        - { path: ^/admin/(login|register|password), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: ROLE_MEMBER_EXPIRED }
        - { path: ^/admin/company, roles: ROLE_COMPANY_MANAGER }
        - { path: ^/blog, roles: IS_AUTHENTICATED_ANONYMOUSLY, ips: [217.70.189.71, 127.0.0.1, 192.168.42.1] }
        - { path: ^/blog, roles: ROLE_NO_ACCESS }
        - { path: ^/event/\w+/tickets/paybox-callback, roles: IS_AUTHENTICATED_ANONYMOUSLY, ips: "%paybox_ips%" }
        - { path: ^/event/\w+/tickets/paybox-callback, roles: ROLE_NO_ACCESS }

    role_hierarchy:
        ROLE_USER: [ROLE_MEMBER_EXPIRED]
        ROLE_COMPANY_MANAGER: [ROLE_USER]
        ROLE_ADMIN:       [ROLE_USER, ROLE_DEPLOY, ROLE_APERO, ROLE_ANNUAIRE, ROLE_FORUM, ROLE_SITE]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
