# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    my_github_authenticator:
        class: AppBundle\Security\MyGithubAuthenticator
        autowire: true

    github_user_repository:
        class: AppBundle\Model\Repository\GithubUserRepository
        factory: ["@ting", get]
        arguments: [AppBundle\Model\Repository\GithubUserRepository]

    app_twig:
        class: AppBundle\Twig\TwigExtension
        tags:
            -  { name: twig.extension }

    app_admin_listener:
        class: AppBundle\Listener\AdminRequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }