# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    twitter_api_settings:
        oauth_access_token: "%twitter_oauth_access_token%"
        oauth_access_token_secret: "%twitter_oauth_access_token_secret%"
        consumer_key: "%twitter_consumer_key%"
        consumer_secret: "%twitter_consumer_secret%"

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    my_github_authenticator:
        class: AppBundle\Security\MyGithubAuthenticator
        autowire: true

    github_user_repository:
        class: AppBundle\Event\Model\Repository\GithubUserRepository
        factory: ["@ting", get]
        arguments: [AppBundle\Event\Model\Repository\GithubUserRepository]

    app_twig:
        class: AppBundle\Twig\TwigExtension
        arguments: ["@app.legacy_router"]
        tags:
            -  { name: twig.extension }

    app.locale_listener:
        class: AppBundle\Listener\LocaleListener
        arguments: [ "%kernel.default_locale%" ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 100 }

    app.legacy_listener:
        class: AppBundle\Listener\LegacySiteListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, priority: 100 }

    app.speaker_repository:
        class: AppBundle\Event\Model\Repository\SpeakerRepository
        factory: ["@ting", get]
        arguments: [AppBundle\Event\Model\Repository\SpeakerRepository]

    app.speaker_factory:
        class: AppBundle\CFP\SpeakerFactory
        arguments: ["@security.token_storage", "@app.speaker_repository"]

    app.talk_voter:
        class: AppBundle\Security\TalkVoter
        arguments: ["@app.speaker_repository"]
        tags:
          - { name: security.voter }
        public: false

    app.photo_storage:
        class: AppBundle\CFP\PhotoStorage
        arguments: ["%kernel.root_dir%/../htdocs/uploads/speakers", "/uploads/speakers"]

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.user_repository:
        class: AppBundle\Association\Model\Repository\UserRepository
        factory: ["@ting", get]
        arguments: [AppBundle\Association\Model\Repository\UserRepository]


    app.legacy_authenticator:
        class: AppBundle\Security\LegacyAuthenticator
        autowire: true

    app.unique_validator:
        class: AppBundle\Validator\Constraints\UniqueEntityValidator
        autowire: true
        tags:
            - { name: validator.constraint_validator }

    app.legacy_model_factory:
        class: AppBundle\LegacyModelFactory

    app.company_subscription:
        class: AppBundle\Association\CompanyMembership\SubscriptionManagement
        autowire: true

    app.paybox_factory:
        class: AppBundle\Payment\PayboxFactory

    app.slack_message_factory:
        class: AppBundle\Slack\MessageFactory
        autowire: true

    app.slack_notifier:
        class: AppBundle\Notifier\SlackNotifier
        arguments: ["%slack_url%", "@app.slack_message_factory", "@jms_serializer.serializer"]

    app.legacy_router:
        class: AppBundle\Routing\LegacyRouter
    app.algolia_client:
        class: AlgoliaSearch\Client
        arguments: [%algolia_app_id%, %algolia_backend_api_key%]

    app.joindin.comments:
        class: AppBundle\Joindin\JoindinComments
        arguments: ["@cache.system"]

    app.twitter_api:
        class: TwitterAPIExchange
        arguments: ["%twitter_api_settings%"]

    app.mailchimp_client:
        class: Mailchimp\Mailchimp
        arguments: ["%mailchimp_api_key%"]
        public: false

    app.mailchimp_api:
        class: AppBundle\Mailchimp\Mailchimp
        arguments: ["@app.mailchimp_client"]
