imports:
  - { resource: ../../../app/config/parameters.yml }
  - { resource: services.yml }

parameters:
    locale: fr

framework:
    translator:      { fallbacks: ["%locale%"], enabled: true }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        storage_id: session.storage.php_bridge
        handler_id: ~
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
