planete_flux:
  path: /flux.php
  defaults: {_controller: PlanetePHP\PlaneteFluxAction}

planete_rss:
  path: /rss.php
  defaults: {_controller: PlanetePHP\PlaneteRssAction}

planete:
  path: /{page}
  defaults:
    _controller: PlanetePHP\PlaneteIndexAction
    page: index.php
  requirements:
    page: 'index.php'
