admin_event_room:
  path: /room
  defaults: {_controller: AppBundle:AdminEvent:room}

admin_event_sponsor_ticket:
  path: /sponsor
  defaults: {_controller: AppBundle:AdminEvent:sponsorTicket}

admin_event_sponsor_mail:
  path: /sponsor/mail
  defaults: {_controller: AppBundle:AdminEvent:resendSponsorToken}

admin_event_sponsor_lastcall_mail:
  path: /sponsor/lastcall
  defaults: {_controller: AppBundle:AdminEvent:sendLastCallSponsorToken}

admin_event_stats:
  path: /stats
  defaults: {_controller: AppBundle:AdminEvent:stats}

export_anonymous:
  path: /export
  defaults: {_controller: AppBundle:AdminEvent:exportAnonymousData}

admin_event_pending_bankwires:
  path: /bankwires
  defaults: {_controller: AppBundle:AdminEvent:pendingBankwires}
