event_index:
  path: /
  defaults: {_controller: AppBundle:Event:index}

event:
  path: /{eventSlug}
  defaults: {_controller: AppBundle:Event:event}

vote_index:
  path: /{eventSlug}/vote
  defaults: {_controller: AppBundle:Vote:index, all: false}

vote_all:
  path: /{eventSlug}/vote-all
  defaults: {_controller: AppBundle:Vote:index, all: true}

vote_new:
  path: /{eventSlug}/vote/new/{talkId}
  defaults: {_controller: AppBundle:Vote:new}
  methods:  [POST]
  requirements:
    talkId: '\d+'

cfp:
  path: /{eventSlug}/cfp
  defaults: {_controller: AppBundle:CFP:index}

cfp_speaker:
  path: /{eventSlug}/cfp/speaker
  defaults: {_controller: AppBundle:CFP:speaker}

cfp_propose:
  path: /{eventSlug}/cfp/propose
  defaults: {_controller: AppBundle:CFP:propose}

cfp_edit:
  path: /{eventSlug}/cfp/{talkId}
  defaults: {_controller: AppBundle:CFP:edit}
  requirements:
    talkId: '\d+'

cfp_invite:
  path: /{eventSlug}/cfp/invite/{talkId}-{token}
  defaults: {_controller: AppBundle:CFP:invite}
  requirements:
    talkId: '\d+'
    token: '.+'