event_index:
  path: /
  defaults: {_controller: AppBundle:Event:index}

event:
  path: /{eventSlug}
  defaults: {_controller: AppBundle:Event:event}

vote_index:
  path: /{eventSlug}/vote
  defaults: {_controller: AppBundle:Vote:index, all: false, page: 1}

vote_index_paginated:
  path: /{eventSlug}/vote/{page}
  defaults: {_controller: AppBundle:Vote:index, all: false}
  requirements:
    page: '\d+'

vote_all:
  path: /{eventSlug}/vote-all
  defaults: {_controller: AppBundle:Vote:index, all: true, page: 1}

vote_all_paginated:
  path: /{eventSlug}/vote-all/{page}
  defaults: {_controller: AppBundle:Vote:index, all: true}
  requirements:
    page: '\d+'

vote_new:
  path: /{eventSlug}/vote/new/{talkId}
  defaults: {_controller: AppBundle:Vote:new}
  methods:  [POST]
  requirements:
    talkId: '\d+'

cfp:
  path: /{eventSlug}/cfp
  defaults: {_controller: AppBundle:CFP:index}

cfp_speaker:
  path: /{eventSlug}/cfp/speaker
  defaults: {_controller: AppBundle:CFP:speaker}

cfp_propose:
  path: /{eventSlug}/cfp/propose
  defaults: {_controller: AppBundle:CFP:propose}

cfp_edit:
  path: /{eventSlug}/cfp/{talkId}
  defaults: {_controller: AppBundle:CFP:edit}
  requirements:
    talkId: '\d+'

cfp_invite:
  path: /{eventSlug}/cfp/invite/{talkId}-{token}
  defaults: {_controller: AppBundle:CFP:invite}
  requirements:
    talkId: '\d+'
    token: '.+'

sponsor_ticket_home:
  path: /{eventSlug}/tickets/sponsor
  defaults: {_controller: AppBundle:Ticket:sponsorTicket}

sponsor_ticket_form:
  path: /{eventSlug}/tickets/sponsor-form
  defaults: {_controller: AppBundle:Ticket:sponsorTicketForm}

ticket:
  path: /{eventSlug}/tickets
  defaults: {_controller: AppBundle:Ticket:ticket}

ticket_payment:
  path: /{eventSlug}/tickets/payment
  defaults: {_controller: AppBundle:Ticket:payment}

ticket_paybox_callback:
  path: /{eventSlug}/tickets/paybox-callback
  defaults: {_controller: AppBundle:Ticket:payboxCallback}

ticket_paybox_redirect:
  path: /{eventSlug}/tickets/paybox-redirect
  defaults: {_controller: AppBundle:Ticket:payboxRedirect}

sponsor_leads:
  path: /{eventSlug}/sponsor/become-sponsor
  defaults: {_controller: AppBundle:Lead:becomeSponsor}

sponsor_leads_post:
  path: /{eventSlug}/sponsor/thank-you
  defaults: {_controller: AppBundle:Lead:postLead}
