event_index:
  path: /
  defaults: {_controller: AppBundle:Event:index}

event:
  path: /{eventSlug}
  defaults: {_controller: AppBundle:Event:event}

vote_index:
  path: /{eventSlug}/vote
  defaults: {_controller: AppBundle:Vote:index}
  requirements:
    eventId: '\d+'

vote_new:
  path: /{eventSlug}/vote/new/{talkId}
  defaults: {_controller: AppBundle:Vote:new}
  methods:  [POST]
  requirements:
    eventId: '\d+'

cfp:
  path: /{eventSlug}/cfp
  defaults: {_controller: AppBundle:Event:cfp}