legacy_forum2008_conferenciers:
  path: /pages/forumphp2008/conferenciers.php
  defaults:
    _controller: AppBundle\Controller\Legacy\Forum2008ConferenciersAction

legacy_forum2008_resumes:
  path: /pages/forumphp2008/resumes.php
  defaults:
    _controller: AppBundle\Controller\Legacy\Forum2008ResumesAction

legacy_forum2008_sessions:
  path: /pages/forumphp2008/sessions.php
  defaults:
    _controller: AppBundle\Controller\Legacy\Forum2008SessionsAction

legacy_forum2009_agenda:
  path: /pages/forumphp2009/agenda.php
  defaults:
    _controller: AppBundle\Controller\Legacy\Forum2009AgendaAction

legacy_forum2009_conferenciers:
  path: /pages/forumphp2009/conferenciers.php
  defaults:
    _controller: AppBundle\Controller\Legacy\Forum2009ConferenciersAction

legacy_forum2009_resumes:
  path: /pages/forumphp2009/resumes.php
  defaults:
    _controller: AppBundle\Controller\Legacy\Forum2009ResumesAction

legacy_forum2009_projets_php:
  path: /pages/forumphp2009/projets-php.php
  defaults:
    _controller: AppBundle\Controller\Legacy\Forum2009ProjetsPhpAction

legacy_forum2009_sessions:
  path: /pages/forumphp2009/sessions.php
  defaults:
    _controller: AppBundle\Controller\Legacy\Forum2009SessionsAction

legacy_event:
  path: /pages/forumphp{year}/{page}
  defaults:
    _controller: AppBundle\Controller\Legacy\LegacyEventAction
    page: index.php
  requirements:
    year: '200[5-9]'
    page: '[a-z0-9-_]+.php'

legacy_rendezvous:
  path: /pages/rendezvous/{page}
  defaults:
    _controller: AppBundle\Controller\RendezVous\RendezVousIndexAction
    page: index.php
  requirements:
    page: 'index.php'

legacy_rendezvous_archive:
  path: /pages/rendezvous/archive.php
  defaults:
    _controller: AppBundle\Controller\RendezVous\RendezVousArchiveAction

legacy_rendezvous_archives:
  path: /pages/rendezvous/archives.php
  defaults:
    _controller: AppBundle\Controller\RendezVous\RendezVousArchivesAction

legacy_rendezvous_confirmation:
  path: /pages/rendezvous/confirmation.php
  defaults:
    _controller: AppBundle\Controller\RendezVous\RendezVousConfirmationAction
