legacy_event:
  path: /pages/forumphp{year}/{page}
  defaults:
    _controller: AppBundle\Controller\Legacy\LegacyEventAction
    page: index.php
  requirements:
    year: '200[5-9]'
    page: '[a-z0-9_]+.php'
