meetups_list:
  path: /
  defaults: {_controller: AppBundle:Meetups:list}
  options:
    sitemap: true

meetups_scrapper:
  path: /scrapping/{antenne}/
  defaults: {_controller: AppBundle:Meetups:scrapMeetup}
