become_member:
  path: /devenir-membre
  defaults: {_controller: AppBundle:MemberShip:becomeMember}

company_membership:
  path: /adherer/entreprise
  defaults: {_controller: AppBundle:MemberShip:company}

company_membership_payment:
  path: /adherer/entreprise/paiement-{invoiceNumber}-{token}
  defaults: {_controller: AppBundle:MemberShip:payment}
  requirements:
    invoiceNumber: 'COTIS-[0-9]{4}-[0-9]+'
    token: '.+'

company_membership_invoice:
  path: /adherer/entreprise/invoice-{invoiceNumber}-{token}
  defaults: {_controller: AppBundle:MemberShip:invoice}
  requirements:
    invoiceNumber: 'COTIS-[0-9]{4}-[0-9]+'
    token: '.+'

company_invitation:
  path: /adherer/invitation/{invitationId}-{token}
  defaults: {_controller: AppBundle:MemberShip:memberInvitation}
  requirements:
    invitationId: '\d+'
    token: '.+'

offices:
  path: /antennes
  defaults: {_controller: AppBundle:Static:offices}

superapero:
  path: /super-apero-8-mars-2018
  defaults: {_controller: AppBundle:Static:superApero}

void:
  path: /void-route
  defaults: {_controller: AppBundle:Static:void}

newsletter_subscribe:
  path: /newsletter-subscribe
  defaults: {_controller: AppBundle:Newsletter:subscribe}

membership_payment:
  path: /paybox-callback
  defaults: {_controller: AppBundle:MemberShip:payboxCallback}

techletter:
  path: /techletter
  defaults: {_controller: AppBundle:Techletter:index}

techletter_subscribe:
  path: /techletter/subscription
  defaults: {_controller: AppBundle:Techletter:subscribe }
  methods: ["POST"]

techletter_webhook:
  path: /techletter/webhook
  defaults: {_controller: AppBundle:Techletter:webhook }
  methods: ["GET", "POST"]
