become_member:
  path: /devenir-membre
  defaults: {_controller: AppBundle:MemberShip:becomeMember}

company_membership:
  path: /adherer/entreprise
  defaults: {_controller: AppBundle:MemberShip:company}

company_invitation:
  path: /adherer/invitation/{invitationId}-{token}
  defaults: {_controller: AppBundle:MemberShip:memberInvitation}
  requirements:
    invitationId: '\d+'
    token: '.+'
