become_member:
  path: /devenir-membre
  defaults: {_controller: AppBundle:MemberShip:becomeMember}

company_membership:
  path: /adherer/entreprise
  defaults: {_controller: AppBundle:MemberShip:company}

company_membership_payment:
  path: /adherer/entreprise/paiement-{invoiceNumber}-{token}
  defaults: {_controller: AppBundle:MemberShip:payment}
  requirements:
    invoiceNumber: 'COTIS-[0-9]{4}-[0-9]+'
    token: '.+'

company_membership_invoice:
  path: /adherer/entreprise/invoice-{invoiceNumber}-{token}
  defaults: {_controller: AppBundle:MemberShip:invoice}
  requirements:
    invoiceNumber: 'COTIS-[0-9]{4}-[0-9]+'
    token: '.+'

company_invitation:
  path: /adherer/invitation/{invitationId}-{token}
  defaults: {_controller: AppBundle:MemberShip:memberInvitation}
  requirements:
    invitationId: '\d+'
    token: '.+'

offices:
  path: /antennes
  defaults: {_controller: AppBundle:Static:offices}

superapero:
  path: /super-apero-9-mars
  defaults: {_controller: AppBundle:Static:superApero}

superapero_live:
  path: /super-apero-9-mars/live
  defaults: {_controller: AppBundle:Static:superAperoLive}

void:
  path: /void-route
  defaults: {_controller: AppBundle:Static:void}

newsletter_subscribe:
  path: /newsletter-subscribe
  defaults: {_controller: AppBundle:Newsletter:subscribe}
